data_transforms:
  a_min: 0
  a_max: 255
  img_size: 512
  use_random_crop: False
  use_rotation: True
  rotation_angle: 10
  use_saturation: False
  saturation: 2
  use_brightness: False
  brightness: 2
  use_horizontal_flip: True
  use_cjitter: False
  use_affine: False
data:
  name: ATR
  root_path: '/media/ubuntu/New Volume/jay/ATR/atr_dataset/cegr'
  label_list: [1,2,3,4,5,6,7,8]
  label_names: ['SUV Vehicle', '2S3 Vehicle', 'ZSU23 Vehicle', 'BRDM2 Vehicle', 'BMP2 Vehicle', 'T72 Vehicle', 'Pickup Vehicle', 'BTR70 Vehicle']
  volume_channel: 2
  negative_to_positive_ratio: -1
