data_transforms:
  a_min: 0
  a_max: 255
  img_size: 1024
  use_random_crop: False
  use_rotation: True
  rotation_angle: 25
  use_saturation: True
  saturation: 2
  use_brightness: True
  brightness: 2
  use_horizontal_flip: True
data:
  name: Polyp
  root_path: '/media/ubuntu/New Volume/jay/Polyp2'
  label_list: [1]
  label_names: ['Polyp']
  volume_channel: 2
  negative_to_positive_ratio: -1
