sam:
  img_size: 512
  num_classes: 2

img_type: 'image'
arch: "Prompt Adapted SAM"
use_fdn: False
decoder_training: 'none'
mlp_transform: False

prompts:
  USE_TEXT_PROMPT: True
  USE_IMAGE_PROMPT: False
  USE_SLICE_NUM: False
  LOCATION: 'prepend'
  DROPOUT: 0
  NUM_TOKENS: 5

training:
  optimizer: 'adamw'
  lr: 1e-3
  batch_size: 32
  num_epochs: 1000
  schedule_step: 1000
  schedule_step_factor: 0.5
  weight_decay: 1e-2
  loss: 'focal'
  reg_multiplier: 0

use_lora: False